### ISSUE TITLE
大佬，今天突然获取不到进度条了

### ISSUE THREAD

**Issue by unwound955** [xrervip/AutoYuketangforHIT#1]
大佬，今天突然获取不到进度条了

D:\OneDrive\文档\git\AutoYuketangforHIT-master>D:\OneDrive\文档\git\AutoYuketangforHIT-master\雨课堂forHIT.py
D:\OneDrive\文档\git\AutoYuketangforHIT-master\雨课堂forHIT.py:296: DeprecationWarning: use options instead of chrome_options
  self.driver = webdriver.Chrome(chrome_options=chrome_options)

DevTools listening on ws://127.0.0.1:61844/devtools/browser/4848d76b-875b-4180-af14-4d99064af6fc
成功配置chrome驱动
读取json文件
登录雨课堂
成功登录雨课堂
当前课程ID：$4360375$
检测到校验位，已从历史记录中获取链接
全部链接已就绪
https://fzuyjsy.yuketang.cn/pro/lms/85RmuqRaA4M/4360375/video/3942979
正在播放:
任务进度：任务进度元素加载失败
Traceback (most recent call last):
  File "D:\OneDrive\文档\git\AutoYuketangforHIT-master\雨课堂forHIT.py", line 369, in <module>
    AutoYuketangforHIT(mode)
  File "D:\OneDrive\文档\git\AutoYuketangforHIT-master\雨课堂forHIT.py", line 65, in __init__
    self.PlayAllVideo('url_list.txt')
  File "D:\OneDrive\文档\git\AutoYuketangforHIT-master\雨课堂forHIT.py", line 79, in PlayAllVideo
    self.PlayVideo(url)
  File "D:\OneDrive\文档\git\AutoYuketangforHIT-master\雨课堂forHIT.py", line 109, in PlayVideo
    self.wait_and_getText(
  File "D:\OneDrive\文档\git\AutoYuketangforHIT-master\雨课堂forHIT.py", line 342, in wait_and_getText
    element = self.wait_element_path(element_xpath)
  File "D:\OneDrive\文档\git\AutoYuketangforHIT-master\雨课堂forHIT.py", line 320, in wait_element_path
    element = WebDriverWait(self.driver, 30).until(
  File "C:\Users\wu__c\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by unwound955** [comment]
大佬  我弄好啦  爱你

**Comment by AndyPJL** [comment]
> 大佬 我弄好啦 爱你

方便告诉一下怎么解决的吗 T.T

**Comment by unwound955** [comment]
> > 大佬 我弄好啦 爱你
> 
> 方便告诉一下怎么解决的吗 T.T


[雨课堂forHIT.log](https://github.com/xrervip/AutoYuketangforHIT/files/5540908/forHIT.log)

把后缀改成.py

**Comment by AndyPJL** [comment]
> > > 大佬我弄好啦爱你
> > 
> > 
> > 方便告诉一下怎么解决的吗吗
> 
> [雨课堂forHIT.log](https://github.com/xrervip/AutoYuketangforHIT/files/5540908/forHIT.log)
> 
> 把后缀改成.py



> > > 大佬我弄好啦爱你
> > 
> > 
> > 方便告诉一下怎么解决的吗吗
> 
> [雨课堂forHIT.log](https://github.com/xrervip/AutoYuketangforHIT/files/5540908/forHIT.log)
> 
> 把后缀改成.py

谢谢大佬，我的问题解决了
